version: "3.8"

services:
  accounts:
    image: cristiii/ms-accounts:latest
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bank
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  loans:
    image: cristiii/ms-loans:latest
    ports:
      - "8081:8081"
    networks:
      - bank-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bank
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  cards:
    image: cristiii/ms-cards:latest
    ports:
      - "8082:8082"
    networks:
      - bank-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bank
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    container_name: ms-bank-postgres
    environment:
      - POSTGRES_PASSWORD=bank
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - bank-network
networks:
  bank-network:
